--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DaDevGuy/EconomyRename
build-by-default: true
branches:
- main
projects:
  EconomyRename:
    path: ""
    libs:
      - src: David-pm-pl/libEco/libEco
        version: ^2.0.0
        branch: stable
    lint:
      phpstan: false
...
