name: EconomyRename
author: DaDevGuy
main: EconomyRename\DaDevGuy\Main
version: 2.0.0
api: [4.0.0]
description: Easy Economy Rename Plugin

commands: 
 rename: 
  description: Rename Items
  permission: economyrename.use
permissions:
 economyrename.use:
  default: op
